name: diesch-autenrieth
favicon: null
layout_spectrum: 0.8104810831137002
typography_spectrum: 0.8947535546030849
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4730234674643725
  lightness: 0.8411397498566657
  saturation: 0.6226957335602492
  rhythmicContrast: 0.16378650139085948
purpose: []
